// Inline style objects shared across the Kōdo WebView components.
export const styles = {
  root: {
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    fontSize: 'var(--vscode-editor-font-size, 13px)',
    background: 'var(--vscode-editor-background)',
    color: 'var(--vscode-editor-foreground)',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    padding: '12px',
    boxSizing: 'border-box',
  },
  inactiveMsg: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--vscode-descriptionForeground)',
    textAlign: 'center' as const,
    padding: '24px',
  },
  attachBtn: {
    background: 'transparent',
    color: '#c8a400',
    border: '1px solid #c8a400',
    borderRadius: '2px',
    width: '40px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  attachArea: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignContent: 'flex-start',
    alignItems: 'flex-start',
    gap: '4px',
    overflowY: 'auto' as const,
    paddingRight: '8px',
  },
  attachChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    maxWidth: '140px',
    boxSizing: 'border-box' as const,
    padding: '2px 6px',
    border: '1px solid #c8a400',
    borderRadius: '6px',
    background: 'transparent',
    fontSize: '11px',
    height: '22px',
  },
  attachChipName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  attachChipRemove: {
    flexShrink: 0,
    cursor: 'pointer',
    fontSize: '11px',
    lineHeight: 1,
  },
  globalStopBtn: {
    background: 'transparent',
    color: 'var(--vscode-errorForeground)',
    border: '1px solid var(--vscode-errorForeground)',
    borderRadius: '2px',
    width: '40px',
    cursor: 'pointer',
    fontSize: '16px',
    flexShrink: 0,
  },
  deleteBtn: {
    background: 'transparent',
    color: 'var(--vscode-errorForeground)',
    border: '1px solid var(--vscode-errorForeground)',
    borderRadius: '2px',
    width: '40px',
    cursor: 'pointer',
    fontSize: '16px',
    flexShrink: 0,
  },
  resumeBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'var(--vscode-notifications-background, var(--vscode-editor-background))',
    border: '1px solid var(--vscode-focusBorder)',
    borderRadius: '4px',
    padding: '6px 10px',
    marginBottom: '6px',
    fontSize: '12px',
  },
  resumeText: { flex: 1 },
  resumeBtn: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '2px',
    padding: '3px 10px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  resumeDismissBtn: {
    background: 'transparent',
    color: 'var(--vscode-descriptionForeground)',
    border: 'none',
    cursor: 'pointer',
    fontSize: '11px',
    flexShrink: 0,
  },
  pingBtn: {
    background: 'var(--vscode-button-secondaryBackground, var(--vscode-button-background))',
    color: 'var(--vscode-button-secondaryForeground, var(--vscode-button-foreground))',
    border: 'none',
    borderRadius: '2px',
    padding: '2px 8px',
    cursor: 'pointer',
    fontSize: '11px',
  },
  pongLine: {
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '11px',
    marginBottom: '4px',
  },
  usagePanel: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '6px',
    padding: '4px 0',
    borderBottom: '1px solid var(--vscode-panel-border)',
  },
  usageName: { marginBottom: '2px', color: 'var(--vscode-foreground)' },
  usageCostLine: { display: 'flex', alignItems: 'center', flexWrap: 'wrap' as const, gap: '2px' },
  usageTotal: { fontVariantNumeric: 'tabular-nums' },
  usageDetail: { opacity: 0.8 },
  compactBtn: {
    marginLeft: '8px',
    background: 'transparent',
    color: 'var(--vscode-textLink-foreground)',
    border: '1px solid var(--vscode-textLink-foreground)',
    borderRadius: '2px',
    padding: '1px 8px',
    cursor: 'pointer',
    fontSize: '10px',
    flexShrink: 0,
  },
  compactBtnDisabled: {
    marginLeft: '8px',
    background: 'transparent',
    color: 'var(--vscode-descriptionForeground)',
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '2px',
    padding: '1px 8px',
    cursor: 'default',
    fontSize: '10px',
    opacity: 0.6,
    flexShrink: 0,
  },
  modeControls: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '6px',
    marginTop: '6px',
    marginBottom: '8px',
  },
  // Toggle cell — the flex item that shares the row evenly, holding the button
  // (which fills it) plus the trailing ⓘ marker.
  modeBtnWrap: {
    flex: 1,
    minWidth: '150px',
    display: 'flex',
    alignItems: 'center',
    // Fixed gap between the button and its trailing ⓘ marker (the button no
    // longer stretches, so this is the actual visible spacing).
    gap: '1px',
  },
  modeBtn: {
    // Size to content so the ⓘ sits a fixed gap away instead of being pushed
    // to the far edge of the (stretched) cell.
    minWidth: 0,
    padding: '4px 8px',
    fontSize: '14px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    background: 'var(--vscode-button-secondaryBackground, var(--vscode-button-background))',
    color: 'var(--vscode-button-secondaryForeground, var(--vscode-button-foreground))',
  },
  // Greyed-out look applied when a toggle is disabled — most notably when Edit/
  // Tool Control are auto-locked to their forced posture under Autonomous —
  // so the user gets a visual cue that the state is fixed and not clickable.
  modeBtnDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed' as const,
  },
  // The ⓘ marker, rendered one step larger than the button text (+2px) and
  // dimmed; it is the sole tooltip trigger for each toggle.
  modeInfo: {
    fontSize: '16px',
    lineHeight: 1,
    cursor: 'help',
    opacity: 0.7,
    flex: 'none' as const,
  },
  // Tooltip wrapper — wraps only the ⓘ marker, anchoring its bubble.
  tooltipWrap: {
    position: 'relative' as const,
    display: 'inline-flex',
  },
  tooltipBox: {
    position: 'absolute' as const,
    bottom: 'calc(100% + 6px)',
    right: 0,
    width: '230px',
    maxWidth: '90vw',
    boxSizing: 'border-box' as const,
    padding: '6px 9px',
    fontSize: '12px',
    lineHeight: 1.4,
    // pre-line (not normal) so the status line's embedded '\n' always starts
    // on its own line, while ordinary spaces still wrap normally.
    whiteSpace: 'pre-line' as const,
    textAlign: 'left' as const,
    background: 'var(--vscode-editorHoverWidget-background, var(--vscode-editorWidget-background))',
    color: 'var(--vscode-editorHoverWidget-foreground, var(--vscode-editorWidget-foreground))',
    border: '1px solid var(--vscode-editorHoverWidget-border, var(--vscode-widget-border))',
    borderRadius: '4px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.35)',
    zIndex: 1000,
    pointerEvents: 'none' as const,
  },
  // Override applied to the leftmost toggle's tooltip so it opens rightward
  // (anchored to the ⓘ's left edge) instead of leftward — otherwise the 230px
  // box runs off the WebView's left edge and gets clipped.
  tooltipBoxLeft: {
    right: 'auto' as const,
    left: 0,
  },
  stream: {
    flex: 1,
    overflowY: 'auto',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    borderTop: '1px solid var(--vscode-panel-border)',
    paddingTop: '8px',
    marginBottom: '8px',
    minHeight: '80px',
  },
  userPrompt: {
    // Shrink-to-fit chat bubble pinned to the right edge (marginLeft:auto), so
    // it no longer spans the full WebView width and grows with its content
    // (including any attached-file chips below the text).
    background: 'var(--vscode-input-background)',
    // Yellow-ish accent matching the active prompt edit box / attach-file chips.
    border: '1px solid #c8a400',
    borderRadius: '6px',
    padding: '12px 20px',
    marginTop: '40px',
    marginBottom: '40px',
    marginLeft: 'auto',
    width: 'fit-content',
    maxWidth: '85%',
    boxSizing: 'border-box' as const,
    color: 'var(--vscode-input-foreground)',
    // Match the agent-response font (inherited editor font), one notch larger.
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    fontSize: 'calc(var(--vscode-editor-font-size, 13px) + 2px)',
    textAlign: 'right',
  },
  userPromptText: {
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  userPromptAttachments: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '4px',
    justifyContent: 'flex-end',
    marginTop: '8px',
  },
  sentAttachChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    maxWidth: '160px',
    boxSizing: 'border-box' as const,
    padding: '2px 8px',
    border: '1px solid #c8a400',
    borderRadius: '6px',
    background: 'transparent',
    fontSize: '11px',
    height: '22px',
    cursor: 'pointer',
    textAlign: 'left' as const,
  },
  sentAttachIcon: {
    flexShrink: 0,
    fontSize: '11px',
    lineHeight: 1,
  },
  agentTokens: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  mdRoot: {
    whiteSpace: 'normal' as const,
    wordBreak: 'break-word' as const,
    lineHeight: 1.5,
  },
  mdP: {
    margin: '0.4em 0',
  },
  mdHeadingBase: {
    fontWeight: 600,
    lineHeight: 1.3,
    margin: '0.6em 0 0.3em',
  },
  mdBold: {
    fontWeight: 600,
  },
  mdCode: {
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    fontSize: '0.9em',
    background: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,0.18))',
    padding: '0.1em 0.3em',
    borderRadius: '3px',
  },
  mdPreWrap: {
    position: 'relative' as const,
    margin: '0.5em 0',
  },
  mdPre: {
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    fontSize: '0.9em',
    background: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,0.12))',
    padding: '8px 10px',
    borderRadius: '4px',
    overflowX: 'auto' as const,
    margin: 0,
    whiteSpace: 'pre' as const,
  },
  mdCopyBtn: {
    position: 'absolute' as const,
    top: '6px',
    right: '6px',
    background: 'var(--vscode-editor-background)',
    color: 'var(--vscode-descriptionForeground)',
    border: '1px solid var(--vscode-descriptionForeground)',
    borderRadius: '2px',
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '12px',
    padding: 0,
  },
  mdUl: {
    margin: '0.3em 0',
    paddingLeft: '1.4em',
  },
  mdOl: {
    margin: '0.3em 0',
    // The message font is the (typically monospace) VS Code editor font, whose
    // digits are wider than a proportional font's — 1.4em clips the "1" down
    // to just its trailing dot. 2.4em leaves room for two-digit markers too.
    paddingLeft: '2.4em',
  },
  mdLi: {
    margin: '0.15em 0',
  },
  mdTableWrap: {
    overflowX: 'auto' as const,
    margin: '0.5em 0',
  },
  mdTable: {
    borderCollapse: 'collapse' as const,
    borderSpacing: 0,
    width: 'max-content',
    maxWidth: '100%',
  },
  mdTh: {
    border: '1px solid var(--vscode-panel-border, rgba(127,127,127,0.4))',
    padding: '4px 10px',
    textAlign: 'left' as const,
    fontWeight: 600,
    background: 'rgba(127,127,127,0.14)',
  },
  mdTd: {
    border: '1px solid var(--vscode-panel-border, rgba(127,127,127,0.4))',
    padding: '4px 10px',
  },
  mdQuote: {
    borderLeft: '3px solid var(--vscode-textBlockQuote-border, rgba(127,127,127,0.4))',
    margin: '0.5em 0',
    padding: '0.2em 0 0.2em 0.8em',
    color: 'var(--vscode-descriptionForeground)',
  },
  mdHr: {
    border: 'none',
    borderTop: '1px solid var(--vscode-panel-border, rgba(127,127,127,0.3))',
    margin: '0.8em 0',
  },
  mdLink: {
    color: 'var(--vscode-textLink-foreground)',
    textDecoration: 'underline' as const,
  },
  kodoBody: {
    flex: 1,
    minWidth: 0,
  },
  awaitingLine: {
    color: 'var(--vscode-descriptionForeground)',
    fontStyle: 'italic',
    fontSize: '12px',
    marginTop: '6px',
    marginBottom: '4px',
    letterSpacing: '0.02em',
  },
  statusResponse: {
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '11px',
    marginTop: '4px',
    marginBottom: '2px',
    fontStyle: 'italic',
  },
  thinkingBlock: {
    marginTop: '6px',
    marginBottom: '4px',
    fontSize: '12px',
  },
  thinkingSummary: {
    cursor: 'pointer',
    color: 'var(--vscode-descriptionForeground)',
    fontStyle: 'italic',
    userSelect: 'none' as const,
    listStyle: 'none',
  },
  thinkingContent: {
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '11px',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    padding: '4px 0 4px 12px',
    borderLeft: '2px solid var(--vscode-panel-border)',
    marginTop: '4px',
  },
  toolgenName: {
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
    borderRadius: '3px',
    padding: '1px 5px',
    fontFamily: 'monospace',
    fontSize: '11px',
    fontWeight: 'bold' as const,
    fontStyle: 'normal' as const,
  },
  toolgenMeta: {
    fontVariantNumeric: 'tabular-nums' as const,
    opacity: 0.8,
    marginTop: '2px',
    fontSize: '11px',
  },
  toolgenDone: {
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '11px',
    fontStyle: 'italic',
    marginTop: '4px',
    marginBottom: '2px',
  },
  toolCall: {
    fontSize: '12px',
    marginTop: '4px',
    marginBottom: '2px',
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '4px',
    alignItems: 'baseline',
  },
  toolCallName: {
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
    borderRadius: '3px',
    padding: '1px 5px',
    fontFamily: 'monospace',
    fontSize: '11px',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  toolCallOk: {
    color: 'var(--vscode-charts-green, var(--vscode-testing-iconPassed, #3fb950))',
    fontWeight: 'bold' as const,
  },
  toolCallFail: {
    color: 'var(--vscode-charts-red, var(--vscode-testing-iconFailed, #f85149))',
    fontWeight: 'bold' as const,
  },
  toolCallDesc: {
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '11px',
  },
  runCommandProgress: {
    fontSize: '11px',
    fontFamily: 'monospace',
    color: 'var(--vscode-descriptionForeground)',
    marginLeft: '4px',
    marginTop: '2px',
    marginBottom: '4px',
    whiteSpace: 'pre' as const,
  },
  runCommandBar: {
    color: 'var(--vscode-charts-blue, var(--vscode-textLink-foreground))',
  },
  webSearchNote: {
    padding: '1px 0',
  },
  webSearchReport: {
    marginTop: '8px',
    paddingTop: '6px',
    borderTop: '1px solid var(--vscode-panel-border)',
  },
  webSearchReportHeading: {
    fontWeight: 'bold' as const,
    marginBottom: '4px',
  },
  webSearchReportRow: {
    marginBottom: '4px',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  toolCallBox: {
    border: '1px solid var(--vscode-widget-border, rgba(128,128,128,0.25))',
    borderRadius: '6px',
    padding: '4px 8px',
    marginTop: '3px',
    marginBottom: '4px',
    marginLeft: '4px',
    background: 'var(--vscode-editorWidget-background, var(--vscode-editor-inactiveSelectionBackground, rgba(128,128,128,0.08)))',
  },
  toolCallBoxClickable: {
    cursor: 'pointer',
  },
  diffLinkBox: {
    color: 'var(--vscode-textLink-foreground)',
    fontSize: '12px',
  },
  // Right-docked group holding the "open this file" / "undo this change" links
  // on a tool call's header row. `marginLeft: auto` absorbs the row's slack so
  // the whole group (and only the group) pins to the right edge, regardless of
  // which of the two links are actually present.
  toolCallActions: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    marginLeft: 'auto',
    flexShrink: 0,
  },
  openFileLink: {
    color: 'var(--vscode-textLink-foreground)',
    fontSize: '11px',
    cursor: 'pointer',
    flexShrink: 0,
    marginRight: '16px',
  },
  undoChangeLink: {
    color: 'var(--vscode-textLink-foreground)',
    fontSize: '11px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  // Right-aligned row hosting the "Rollback / Roll forward to this state" link
  // beneath a tool call's detail box — docked to the right edge like the
  // undo/redo link above it, rather than the old full-width box.
  rollbackRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '3px',
    marginBottom: '4px',
    marginLeft: '4px',
  },
  rollbackLink: {
    display: 'flex',
    alignItems: 'center',
    color: 'var(--vscode-textLink-foreground)',
    fontSize: '11px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  rollbackIcon: {
    fontSize: '14px',
    marginRight: '4px',
  },
  rollforwardIcon: {
    fontSize: '14px',
    marginRight: '4px',
    display: 'inline-block' as const,
    transform: 'scaleX(-1)',
  },
  toolCallWarn: {
    color: 'var(--vscode-editorWarning-foreground, #cca700)',
    fontSize: '11px',
    marginBottom: '4px',
  },
  toolCallTable: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '11px',
  },
  toolCallParamName: {
    verticalAlign: 'top' as const,
    fontFamily: 'monospace',
    fontWeight: 'bold' as const,
    color: 'var(--vscode-descriptionForeground)',
    padding: '1px 8px 1px 0',
    whiteSpace: 'nowrap' as const,
    width: '1%',
  },
  toolCallParamValue: {
    verticalAlign: 'top' as const,
    fontFamily: 'monospace',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    padding: '1px 0',
  },
  // Sub-agent takeover dividers
  // Sub-agent task brief — the structured task handed to a spawned sub-agent.
  // Left-aligned card, deliberately distinct from the user's prompt bubble.
  subagentTask: {
    alignSelf: 'flex-start' as const,
    maxWidth: '85%',
    margin: '2px 0 8px',
    padding: '6px 10px',
    borderLeft: '3px solid var(--vscode-panel-border)',
    background: 'var(--vscode-textBlockQuote-background)',
    borderRadius: '4px',
  },
  subagentTaskLabel: {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '4px',
  },
  subagentTaskText: {
    // Markdown owns the layout now; no pre-wrap so block spacing isn't doubled.
    fontSize: '12px',
    color: 'var(--vscode-foreground)',
  },
  // A just-granted "always allow" security rule notice (WS_PROTOCOL.md §5.9d)
  // — the header row mirrors a tool call's (icon + label), and its details
  // sit in the same boxed/monospace table (toolCallBox/toolCallTable) a tool
  // call uses for its parameters, just with an info icon instead of a
  // success/failure one and only the two rows that matter (command, scope).
  securityRuleAdded: {
    fontSize: '12px',
    marginTop: '4px',
    marginBottom: '2px',
    display: 'flex',
    gap: '4px',
    alignItems: 'baseline',
  },
  securityRuleAddedIcon: {
    flexShrink: 0,
  },
  // Stuck-agent watchdog's continuation nudge (doc/STUCK_DETECTION.md) — the
  // user-facing explanation of why Kōdo told the agent to keep going.
  agentUnstuckNudge: {
    fontSize: '12px',
    marginTop: '4px',
    marginBottom: '2px',
    display: 'flex',
    gap: '4px',
    alignItems: 'baseline',
  },
  agentUnstuckNudgeIcon: {
    flexShrink: 0,
  },
  agentUnstuckNudgeText: {
    color: 'var(--vscode-descriptionForeground)',
  },
  // File events
  fileEvents: {
    borderTop: '1px solid var(--vscode-panel-border)',
    padding: '6px 0',
    marginBottom: '8px',
  },
  fileEventsHeader: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  fileEvent: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    marginBottom: '2px',
  },
  fileEventKind: {
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
    borderRadius: '3px',
    padding: '1px 4px',
    fontSize: '10px',
    flexShrink: 0,
  },
  fileEventPath: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: 'monospace',
  },
  openBtn: {
    background: 'transparent',
    color: 'var(--vscode-textLink-foreground)',
    border: 'none',
    cursor: 'pointer',
    fontSize: '11px',
    padding: '0 4px',
    textDecoration: 'underline',
    flexShrink: 0,
  },
  // Approval gate
  gateCard: {
    border: '1px solid var(--vscode-focusBorder)',
    borderRadius: '4px',
    padding: '10px',
    marginBottom: '8px',
    background: 'var(--vscode-editor-background)',
  },
  gateHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '6px',
  },
  gateType: {
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
    borderRadius: '3px',
    padding: '1px 5px',
    fontSize: '10px',
    fontWeight: 'bold',
  },
  gateTitle: { fontWeight: 'bold', fontSize: '13px' },
  gateSummary: {
    fontSize: '12px',
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '8px',
    fontStyle: 'italic',
  },
  gateArtifact: { marginBottom: '8px' },
  gateActions: { display: 'flex', flexDirection: 'column', gap: '6px' },
  gateTopRow: { display: 'flex', gap: '8px', alignItems: 'center' },
  agreeBtn: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '2px',
    padding: '6px 16px',
    cursor: 'pointer',
    fontWeight: 'bold',
    alignSelf: 'flex-start',
  },
  stopBtn: {
    background: 'transparent',
    color: 'var(--vscode-errorForeground)',
    border: '1px solid var(--vscode-errorForeground)',
    borderRadius: '2px',
    padding: '6px 12px',
    cursor: 'pointer',
    fontWeight: 'bold',
    alignSelf: 'flex-start',
  },
  feedbackRow: { display: 'flex', gap: '6px', alignItems: 'flex-end' },
  feedbackInput: {
    flex: 1,
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-input-border)',
    borderRadius: '2px',
    padding: '4px 6px',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    resize: 'none',
  },
  feedbackBtn: {
    background: 'var(--vscode-button-secondaryBackground, var(--vscode-button-background))',
    color: 'var(--vscode-button-secondaryForeground, var(--vscode-button-foreground))',
    border: 'none',
    borderRadius: '2px',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: '12px',
    alignSelf: 'stretch',
  },
  // Security permission prompt (replaces the prompt input while pending)
  permissionCard: {
    border: '1px solid var(--vscode-inputValidation-warningBorder, var(--vscode-focusBorder))',
    borderRadius: '4px',
    padding: '10px',
    marginBottom: '8px',
    background: 'var(--vscode-editor-background)',
  },
  permissionRiskBadge: {
    marginLeft: 'auto',
    background: 'var(--vscode-inputValidation-warningBackground, var(--vscode-badge-background))',
    color: 'var(--vscode-foreground)',
    border: '1px solid var(--vscode-inputValidation-warningBorder, transparent)',
    borderRadius: '3px',
    padding: '1px 6px',
    fontSize: '10px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
  permissionRecoveredBanner: {
    fontSize: '12px',
    lineHeight: '1.4',
    background: 'var(--vscode-inputValidation-warningBackground)',
    color: 'var(--vscode-inputValidation-warningForeground, var(--vscode-foreground))',
    border: '1px solid var(--vscode-inputValidation-warningBorder, transparent)',
    borderRadius: '3px',
    padding: '6px 8px',
    marginBottom: '8px',
  },
  permissionReason: {
    fontSize: '12px',
    marginBottom: '8px',
  },
  permissionIntent: {
    fontSize: '12px',
    color: 'var(--vscode-descriptionForeground)',
    fontStyle: 'italic',
    marginBottom: '8px',
  },
  permissionIntentLabel: {
    fontStyle: 'normal',
    fontWeight: 'bold',
  },
  permissionParams: {
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '3px',
    padding: '6px 8px',
    marginBottom: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    maxHeight: '140px',
    overflowY: 'auto',
  },
  permissionParamRow: {
    display: 'flex',
    gap: '8px',
    fontSize: '11px',
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
  },
  permissionParamName: {
    color: 'var(--vscode-descriptionForeground)',
    flexShrink: 0,
    minWidth: '80px',
  },
  permissionParamValue: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
  },
  // "Always allow <shape>" rule-offer checkboxes (doc/SECURITY_RULES_PLAN.md §2.3)
  permissionRuleOffer: {
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '3px',
    padding: '6px 8px',
    marginBottom: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  permissionRuleOfferLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  permissionRuleOfferShape: {
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    fontWeight: 'bold',
  },
  // Per-part breakdown for a compound command (doc/SECURITY_RULES_PLAN.md §2.6)
  // — only rendered when the ask carries more than one part.
  permissionParts: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '8px',
  },
  permissionPartBlock: {
    borderLeft: '2px solid var(--vscode-panel-border)',
    paddingLeft: '8px',
  },
  permissionPartReason: {
    fontSize: '12px',
    marginBottom: '4px',
  },
  // Stuck-agent watchdog alarm (doc/STUCK_DETECTION.md) — modeled on the
  // permission card's layout, but info-blue rather than warning-amber (this
  // is a behavioral observation, not a security risk) and with no rule
  // checkboxes: there is nothing here to "always allow".
  stuckAlertCard: {
    border: '1px solid var(--vscode-inputValidation-infoBorder, var(--vscode-focusBorder))',
    borderRadius: '4px',
    padding: '10px',
    marginBottom: '8px',
    background: 'var(--vscode-editor-background)',
  },
  stuckAlertReasons: {
    fontSize: '12px',
    lineHeight: '1.5',
    marginBottom: '8px',
    paddingLeft: '18px',
  },
  stuckAlertBtn: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '2px',
    padding: '6px 16px',
    cursor: 'pointer',
    fontWeight: 'bold',
    alignSelf: 'flex-start',
  },
  stuckAlertDismissBtn: {
    background: 'var(--vscode-button-secondaryBackground, transparent)',
    color: 'var(--vscode-button-secondaryForeground, var(--vscode-foreground))',
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '2px',
    padding: '6px 12px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  // ask_user question panel (in-feed, interactive until confirmed)
  askUserPanel: {
    border: '1px solid var(--vscode-focusBorder)',
    borderRadius: '4px',
    padding: '10px',
    marginTop: '12px',
    marginBottom: '12px',
    background: 'var(--vscode-editor-background)',
    // scrollIntoView(block:'start') target — keep a little breathing room so
    // the first question does not sit flush against the panel's top edge.
    scrollMarginTop: '8px',
  },
  askUserPanelFrozen: {
    border: '1px solid var(--vscode-panel-border)',
  },
  askUserQuestionBox: {
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '4px',
    padding: '8px 10px',
    marginBottom: '8px',
  },
  askUserQuestionText: {
    fontSize: '13px',
    fontWeight: 'bold',
    marginBottom: '2px',
  },
  askUserKindHint: {
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '6px',
  },
  askUserOption: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    padding: '4px 6px',
    borderRadius: '3px',
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  askUserOptionFrozen: {
    cursor: 'default',
  },
  askUserOptionSelected: {
    background: 'var(--vscode-list-activeSelectionBackground)',
    color: 'var(--vscode-list-activeSelectionForeground)',
  },
  askUserMark: {
    flexShrink: 0,
    width: '16px',
    textAlign: 'center' as const,
  },
  askUserFreeInput: {
    flex: 1,
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-input-border)',
    borderRadius: '2px',
    padding: '4px 6px',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    resize: 'none',
  },
  askUserFreeTextFrozen: {
    flex: 1,
    fontStyle: 'italic',
    whiteSpace: 'pre-wrap' as const,
  },
  askUserConfirmBtn: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '2px',
    padding: '8px 16px',
    cursor: 'pointer',
    fontWeight: 'bold',
    width: '100%',
  },
  askUserConfirmBtnDisabled: {
    opacity: 0.55,
    cursor: 'default',
  },
  askUserAnsweredNote: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    fontStyle: 'italic',
  },
  // Prompt input
  inputArea: {
    display: 'flex',
    flexDirection: 'column',
  },
  input: {
    width: '100%',
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-input-border)',
    borderRadius: '2px',
    padding: '4px 6px',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    resize: 'none',
    minHeight: '40px',
    maxHeight: '180px',
    overflowY: 'auto',
    boxSizing: 'border-box',
  },
  inputFooter: {
    display: 'flex',
    alignItems: 'center',
    height: '50px',
    paddingTop: '6px',
  },
  footerButtons: {
    display: 'flex',
    gap: '10px',
    alignSelf: 'stretch',
    alignItems: 'stretch',
  },
  sendBtn: {
    background: 'transparent',
    color: '#2ea043',
    border: '1px solid #2ea043',
    borderRadius: '2px',
    width: '40px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  // Wraps a footer button's glyph so it (not the button itself) can be nudged
  // on press, giving the four bottom-bar buttons tactile click feedback.
  footerBtnSymbol: {
    display: 'inline-block',
    transform: 'translate(0, 0)',
    transition: 'transform 0.05s ease-out',
  },
  footerBtnSymbolPressed: {
    display: 'inline-block',
    transform: 'translate(1px, 2px)',
    transition: 'transform 0.05s ease-out',
  },
};
